### ISSUE TITLE
Plan for Vue3

### ISSUE THREAD

**Issue by stafyniaksacha** [savyjs/vuetify-strapi-dashboard#5]
Hello there ! This is an awesome work!
Do you have any plan to support Vue 3?
More globally, do you have a roadmap for this project?

**Comment by savyjs** [comment]
Hi!
Thank you @stafyniaksacha,
Yes, I will publish the roadmap as soon as possible. 
about Vue3, this is a Nuxt module, so we follow the Nuxt (not Vue).
